# Generated by Django 6.0.1 on 2026-02-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
