# Generated by Django 6.0.1 on 2026-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos/'),
        ),
    ]
